services:
  - type: web
    name: evsaarthi-api
    runtime: node
    rootDir: backend/api-gateway
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: INTERNAL_SECRET
        sync: false
      - key: POINTS_SERVICE_URL
        sync: false
      - key: MAPPLS_CLIENT_ID
        sync: false
      - key: MAPPLS_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URLS
        sync: false
